[package]
name = "eip1962-evmc"
version = "0.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[lib]
name = "eip1962"
crate-type = ["staticlib", "cdylib"]

[dependencies]
evmc-sys = { git = "https://github.com/ethereum/evmc", rev = "fbba2538e1c178c9ffa2ed0e3b6ff5b7364706ee" }
evmc-vm = { git = "https://github.com/ethereum/evmc", rev = "fbba2538e1c178c9ffa2ed0e3b6ff5b7364706ee" }
evmc-declare = { git = "https://github.com/ethereum/evmc", rev = "fbba2538e1c178c9ffa2ed0e3b6ff5b7364706ee" }
eth_pairings = { git = "https://github.com/matter-labs/eip1962", rev = "b21c2540f9dc9ec4800eaf67c8c2e66c78731c3c" }
