[package]
name = "eip1962-evmc"
version = "0.1.0"
authors = ["Alex Beregszaszi <alex@rtfs.hu>"]
license = "Apache-2.0"
edition = "2018"
publish = false

[lib]
name = "eip1962"
crate-type = ["staticlib", "cdylib"]

[dependencies]
evmc-sys = { git = "https://github.com/ethereum/evmc", rev = "v6.3.1" }
evmc-vm = { git = "https://github.com/ethereum/evmc", rev = "v6.3.1" }
evmc-declare = { git = "https://github.com/ethereum/evmc", rev = "v6.3.1" }
# 0.1.1
eth_pairings = { git = "https://github.com/matter-labs/eip1962", rev = "07056a7d04557ad253219a1d0f7b901d68307563" }
